# Project: SPSAS
# Makefile created by Red Panda C++ 

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
RES      = SPSAS_private.res
OBJ      = main.o $(RES)
LINKOBJ  = main.o $(RES)
CLEANOBJ  =  main.o $(RES)
LIBS     =  -pg
INCS     =  
CXXINCS  =  
BIN      = SPSAS.exe
CXXFLAGS = $(CXXINCS)  -pg -pipe
CFLAGS   = $(INCS)  -pg -pipe
RM       = del /q /f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(CLEANOBJ) $(BIN) > NUL 2>&1

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c D:/ÎÄµµ/projects/SPSAS/main.cpp -o main.o $(CXXFLAGS)  -finput-charset=gbk -fexec-charset=gbk

SPSAS_private.res: SPSAS_private.rc 
	$(WINDRES) -i SPSAS_private.rc --input-format=rc -o SPSAS_private.res -O coff 

